export const CATEGORIES = [
  "Roofing Companies",
  "HVAC Companies",
  "Plumbing Companies",
  "Electricians",
  "General Contractors",
  "Remodeling Contractors",
  "Kitchen Remodelers",
  "Bathroom Remodelers",
  "Concrete Contractors",
  "Fence Companies",
  "Deck Builders",
  "Flooring Companies",
  "Painting Companies",
  "Drywall Contractors",
  "Siding Contractors",
  "Window Installation Companies",
  "Garage Door Companies",
  "Insulation Contractors",
  "Solar Installation Companies",
  "Landscaping Companies",
  "Tree Service Companies",
  "Lawn Care Companies",
  "Irrigation Companies",
  "Pest Control Companies",
  "Junk Removal Companies",
  "Pressure Washing Companies",
  "Pool Service Companies",
  "Pool Builders",
  "Cleaning Companies",
  "Commercial Cleaning Companies",
  "Carpet Cleaning Companies",
  "Restoration Companies",
  "Water Damage Restoration Companies",
  "Fire Damage Restoration Companies",
  "Moving Companies",
  "Storage Facilities",
  "Property Management Companies",
  "Real Estate Teams",
  "Real Estate Brokerages",
  "Home Inspectors",
  "Appraisers",
  "Insurance Agencies",
  "Mortgage Brokers",
  "Financial Advisors",
  "Accountants",
  "Tax Preparation Services",
  "Bookkeepers",
  "Law Firms",
  "Personal Injury Lawyers",
  "Family Lawyers",
  "Estate Planning Lawyers",
  "Bankruptcy Lawyers",
  "Immigration Lawyers",
  "Dentists",
  "Orthodontists",
  "Chiropractors",
  "Physical Therapists",
  "Med Spas",
  "Dermatologists",
  "Veterinarians",
  "Mental Health Practices",
  "Urgent Care Clinics",
  "Private Medical Practices",
  "Optometrists",
  "Barbershops",
  "Hair Salons",
  "Nail Salons",
  "Beauty Salons",
  "Massage Therapists",
  "Gyms",
  "Personal Trainers",
  "Martial Arts Schools",
  "Yoga Studios",
  "Restaurants",
  "Coffee Shops",
  "Bakeries",
  "Catering Companies",
  "Food Trucks",
  "Event Venues",
  "Wedding Venues",
  "Photography Studios",
  "Videographers",
  "DJ Services",
  "Daycares",
  "Preschools",
  "Tutoring Centers",
  "Private Schools",
  "Pet Groomers",
  "Dog Trainers",
  "Boarding Kennels",
  "Auto Repair Shops",
  "Auto Body Shops",
  "Auto Detailing Companies",
  "Mobile Detailers",
  "Towing Companies",
  "Mobile Mechanics",
  "Transmission Shops",
  "Tire Shops",
  "Glass Repair Companies",
  "Locksmiths",
  "Security Companies",
  "Alarm Installation Companies",
  "IT Service Companies",
  "Managed IT Providers",
  "Computer Repair Shops",
  "Web Design Agencies",
  "Marketing Agencies",
  "Sign Companies",
  "Printing Companies",
  "Staffing Agencies",
  "Recruiting Firms",
  "Courier Services",
  "Delivery Services",
  "Funeral Homes",
  "Senior Care Agencies",
  "Assisted Living Facilities",
  "Nonprofit Organizations",
  "Churches",
  "Construction Companies",
  "Engineering Firms",
  "Architecture Firms",
  "Surveying Companies",
  "Manufacturing Companies",
  "Wholesale Distributors"
];
